version: '3.8'

x-elements-node-env: &elements-node-env
  GENERATE_BLOCK_CONNECTION_NETWORK: elementsregtest
  GENERATE_BLOCK_CONNECTION_HOST: testing-elements:18447
  CONNECTION_PRC_USERID: elementsrpc
  CONNECTION_PRC_PASSWORD: password
  DYNAFED_FEDPEG_SCRIPT: 5121024241bff4d20f2e616bef2f6e5c25145c068d45a78da3ddba433b3101bbe9a37d51ae
  DYNAFED_PAK: 02b6991705d4b343ba192c2d1b10e7b8785202f51679f26a1f2cdbe9c069f8dceb024fb0908ea9263bedb5327da23ff914ce1883f851337d71b3ca09b32701003d05,030e07d4f657c0c169e04fac5d5a8096adb099874834be59ad1e681e22d952ccda0214156e4ae9168289b4d0c034da94025121d33ad8643663454885032d77640e3d

services:
  testing-bitcoin:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.1.1
    container_name: testing-bitcoin
    volumes:
      - ./testing_bitcoin:/workspace
    working_dir: /workspace/
    ports:
      - 18443:18443
    networks:
      - testing_network
    command: >
      bitcoind
      --regtest
      -datadir=/workspace
      -server
      -rpcuser=bitcoinrpc
      -rpcpassword=password
      -port=18442
      -rpcport=18443
      -txindex
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0

  testing-elements:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.1.1
    container_name: testing-elements
    volumes:
      - ./testing_elements1:/workspace
    working_dir: /workspace/
    ports:
      - 18447:18447
    networks:
      - testing_network
    depends_on:
      - testing-bitcoin
    command: >
      elementsd
      -chain=liquidregtest
      -datadir=/workspace
      -server
      -rpcuser=elementsrpc
      -rpcpassword=password
      -port=18446
      -rpcport=18447
      -txindex
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -timeout=10
      -enforce_pak
      -validatepegin
      -mainchainrpchost=testing-bitcoin
      -mainchainrpcport=18443
      -mainchainrpcuser=bitcoinrpc
      -mainchainrpcpassword=password
      -parentpubkeyprefix=111
      -parentscriptprefix=196
      -parent_bech32_hrp=bcrt
      -peginconfirmationdepth=1
      -con_connect_genesis_outputs=1
      -fedpegscript=51
      -signblockscript=51

  testing-elements2:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.1.1
    container_name: testing-elements2
    volumes:
      - ./testing_elements2:/workspace
    working_dir: /workspace/
    ports:
      - 18457:18457
    networks:
      - testing_network
    depends_on:
      - testing-bitcoin
      - testing-elements
    command: >
      elementsd
      -chain=liquidregtest
      -datadir=/workspace
      -server
      -rpcuser=elementsrpc
      -rpcpassword=password
      -rpcport=18457
      -txindex
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -timeout=20
      -addnode=testing-elements:18446
      -enforce_pak
      -validatepegin=0
      -parentpubkeyprefix=111
      -parentscriptprefix=196
      -parent_bech32_hrp=bcrt
      -con_connect_genesis_outputs=1
      -fedpegscript=51
      -signblockscript=51

  generateblock-bin-elements:
    build:
      context: .
      dockerfile: ./tests/testing_alpine3_14.dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace/
    environment: *elements-node-env
    networks:
      - testing_network
    command: /bin/ash -c "./test_generate_ash.sh"

  exec-test:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.1.1
    volumes:
      - ./:/workspace
    working_dir: /workspace/
    networks:
      - testing_network
    command: /bin/bash -c "./tests/test.sh"

networks:
  testing_network:
    driver: bridge
